Refactor index.html
rtbf-ir/rtbf.ir pull request #135
Opened 2022-04-18 10:38 UTC by dashtaki

Here are the changes which have been made in this PR:
- Create `/scripts/index.js` to move the custom script in `index.html`
- Remove unnecessary `jQuery` link from `index.html`
- and so on which is related to clean code

**_Note:_** I know we have a specific [issue](https://github.com/rtbf-ir/rtbf.ir/issues/116) for sorting the data with action but I also tried to sort websites' names alphabetically and I found that in order to make it possible we need to have a specific property for each website object for Persian name, As I see in some cases like [30book](https://github.com/rtbf-ir/rtbf.ir/blob/main/data/data.json#L571) name started with a number or [GoToClass](https://github.com/rtbf-ir/rtbf.ir/blob/main/data/data.json#L331) the name is in English which misleads the sort functionality. Then we have 2 options:

1. Always store Persian translation in the `name` property
2. Have a specific property for Persian translation, For instance: `persian_name`, `name_fr`, or whatever.

I am more on the second option since we try to isolate the names which would be more helpful in terms of scalability.

I just commented on the line for sorting in the code I can also remove it all the way since we want to make it with action so comments, ideas, and suggestions are welcome.

2022-04-19 22:04 UTC, amirshnll requested changes
dear @dashtaki,
I checked the changes. All were approved. Please correct the conflicts and then send PR.
For sorting service, we intend to have a github action that does this sorting automatically after editing the data.json file.
For each service to appear higher in the list of more popular services, it is better to add a priority field to the data.json file.
As for English words, Persian ones should be sorted first and then English ones should be at the bottom of the list. Because services that do not have a Persian name and are registered for the right to be forgotten directory have not a lot of users.
Thanks for your contribution to the right to be forgotten directory.

2022-04-19 22:20 UTC, dashtaki commented
>  - For each service to appear higher in the list of more popular services, it is better to add a priority field to the data.json file.
> - As for English words, Persian ones should be sorted first, and then English ones should be at the bottom of the list. B

First of all thanks for the reply. So based on these 2 points which you mentioned I think in the first place we have to add a new property to each website object as `priority` or `popularity` and then sort the data(by action) first based on that and then sort based on the name(Persian). Please correct me if I am mistaken.

2022-04-20 06:14 UTC, amirshnll approved these changes

2022-04-20 06:15 UTC, amirshnll commented
> > * For each service to appear higher in the list of more popular services, it is better to add a priority field to the data.json file.
> > * As for English words, Persian ones should be sorted first, and then English ones should be at the bottom of the list. B
> 
> First of all thanks for the reply. So based on these 2 points which you mentioned I think in the first place we have to add a new property to each website object as `priority` or `popularity` and then sort the data(by action) first based on that and then sort based on the name(Persian). Please correct me if I am mistaken.

✅ ✅ ✅ ✅

2022-04-20 06:15 UTC, merged